# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleTitle', models.TextField()),
                ('articleContent', models.TextField()),
                ('articleCreatedTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Articles',
            },
        ),
    ]
